# Generated by Django 5.1.15 on 2026-07-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_player_counts'),
        ('tournaments', '0004_scheduled_deadline_chat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentteam',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tournamentmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.UniqueConstraint(fields=('name', 'game'), name='unique_tournament_name_per_game'),
        ),
        migrations.AddConstraint(
            model_name='tournamentteam',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='unique_team_name_per_tournament'),
        ),
    ]
