# Generated by Django 5.1.15 on 2026-07-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidequests', '0003_sidequest_completion_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidequest',
            name='points',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
