from django.core.management.base import BaseCommand
from apps.players.models import Player


class Command(BaseCommand):
    help = "Seed the database with initial players data"

    def handle(self, *args, **options):
        players_data = [
            {"fullname": "Paul John", "nickname": "Paul John", "department": "A"},
            {"fullname": "Abbu", "nickname": "Abbu", "department": "B"},
            {"fullname": "JC", "nickname": "JC", "department": "A"},
            {"fullname": "Wayne", "nickname": "Wayne", "department": "B"},
            {"fullname": "Arcer", "nickname": "Arcer", "department": "B"},
            {"fullname": "Rey", "nickname": "Rey", "department": "A"},
            {"fullname": "Almez", "nickname": "Almez", "department": "B"},
            {"fullname": "Kurt", "nickname": "Kurt", "department": "S"},
            {"fullname": "Yuvie", "nickname": "Yuvie", "department": "A"},
            {"fullname": "RV", "nickname": "RV", "department": "A"},
            {"fullname": "Hannah", "nickname": "Hannah", "department": "B"},
            {"fullname": "Peng", "nickname": "Peng", "department": "B"},
            {"fullname": "Lou", "nickname": "Lou", "department": "A"},
            {"fullname": "Liam", "nickname": "Liam", "department": "B"},
            {"fullname": "Kiev", "nickname": "Kiev", "department": "S"},
            {"fullname": "Kent", "nickname": "Kent", "department": "A"},
            {"fullname": "Yen", "nickname": "Yen", "department": "B"},
            {"fullname": "Ivan C.", "nickname": "Ivan C.", "department": "B"},
            {"fullname": "Daniel", "nickname": "Daniel", "department": "B"},
            {"fullname": "Carlo", "nickname": "Carlo", "department": "B"},
            {"fullname": "Jash", "nickname": "Jash", "department": "A"},
            {"fullname": "Fred", "nickname": "Fred", "department": "A"},
            {"fullname": "Kiko", "nickname": "Kiko", "department": "B"},
            {"fullname": "Martin", "nickname": "Martin", "department": "B"},
            {"fullname": "John", "nickname": "John", "department": "B"},
            {"fullname": "Je", "nickname": "Je", "department": "B"},
            {"fullname": "Miguel", "nickname": "Miguel", "department": "S"},
            {"fullname": "Rone", "nickname": "Rone", "department": "B"},
            {"fullname": "Aerol", "nickname": "Aerol", "department": "A"},
            {"fullname": "Rori", "nickname": "Rori", "department": "A"},
            {"fullname": "Jex", "nickname": "Jex", "department": "S"},
            {"fullname": "CJ", "nickname": "CJ", "department": "B"},
            {"fullname": "Franz", "nickname": "Franz", "department": "A"},
            {"fullname": "Pam", "nickname": "Pam", "department": "EE"},
            {"fullname": "Ilene", "nickname": "Ilene", "department": "TR"},
            {"fullname": "Charl", "nickname": "Charl", "department": "A"},
            {"fullname": "Giles", "nickname": "Giles", "department": "A"},
            {"fullname": "Son", "nickname": "Son", "department": "B"},
            {"fullname": "Paulo", "nickname": "Paulo", "department": "B"},
            {"fullname": "Che", "nickname": "Che", "department": "B"},
            {"fullname": "Janjan", "nickname": "Janjan", "department": "S"},
            {"fullname": "Lex", "nickname": "Lex", "department": "S"},
            {"fullname": "Laur", "nickname": "Laur", "department": "B"},
            {"fullname": "Wangni", "nickname": "Wangni", "department": "A"},
            {"fullname": "Josh", "nickname": "Josh", "department": "A"},
            {"fullname": "Kee", "nickname": "Kee", "department": "B"},
            {"fullname": "Seph", "nickname": "Seph", "department": "B"},
            {"fullname": "Louie", "nickname": "Louie", "department": "B"},
            {"fullname": "Dex", "nickname": "Dex", "department": "B"},
            {"fullname": "Arlene", "nickname": "Arlene", "department": "A"},
            {"fullname": "Jim", "nickname": "Jim", "department": "B"},
            {"fullname": "Paola", "nickname": "Paola", "department": "B"},
            {"fullname": "Jah", "nickname": "Jah", "department": "B"},
            {"fullname": "Chu", "nickname": "Chu", "department": "A"},
            {"fullname": "Sean CD", "nickname": "Sean CD", "department": "A"},
            {"fullname": "Dinds", "nickname": "Dinds", "department": "A"},
            {"fullname": "Evan", "nickname": "Evan", "department": "S"},
            {"fullname": "Jam", "nickname": "Jam", "department": "B"},
            {"fullname": "Cla", "nickname": "Cla", "department": "B"},
            {"fullname": "Rose", "nickname": "Rose", "department": "B"},
            {"fullname": "Kenneth", "nickname": "Kenneth", "department": "A"},
            {"fullname": "Alvin", "nickname": "Alvin", "department": "B"},
            {"fullname": "Jess", "nickname": "Jess", "department": "B"},
            {"fullname": "Kevin", "nickname": "Kevin", "department": "WS"},
            {"fullname": "Erl", "nickname": "Erl", "department": "B"},
            {"fullname": "Shien", "nickname": "Shien", "department": "B"},
            {"fullname": "Kyle", "nickname": "Kyle", "department": "B"},
            {"fullname": "Andy", "nickname": "Andy", "department": "A"},
            {"fullname": "Raffy M.", "nickname": "Raffy M.", "department": "B"},
            {"fullname": "Tyne", "nickname": "Tyne", "department": "A"},
            {"fullname": "Vince", "nickname": "Vince", "department": "B"},
            {"fullname": "Lloyd", "nickname": "Lloyd", "department": "B"},
            {"fullname": "Sage", "nickname": "Sage", "department": "A"},
            {"fullname": "Brett", "nickname": "Brett", "department": "A"},
            {"fullname": "Kahlil", "nickname": "Kahlil", "department": "A"},
            {"fullname": "Alex", "nickname": "Alex", "department": "B"},
            {"fullname": "Robs", "nickname": "Robs", "department": "A"},
            {"fullname": "Jovs", "nickname": "Jovs", "department": "B"},
            {"fullname": "Raffy R.", "nickname": "Raffy R.", "department": "EE"},
            {"fullname": "Miles", "nickname": "Miles", "department": "A"},
            {"fullname": "Sam", "nickname": "Sam", "department": "A"},
            {"fullname": "Clark", "nickname": "Clark", "department": "B"},
            {"fullname": "Arvin", "nickname": "Arvin", "department": "B"},
            {"fullname": "Junjie", "nickname": "Junjie", "department": "A"},
            {"fullname": "Rex", "nickname": "Rex", "department": "B"},
            {"fullname": "Adie", "nickname": "Adie", "department": "A"},
            {"fullname": "Ivan S.", "nickname": "Ivan S.", "department": "B"},
            {"fullname": "Liza", "nickname": "Liza", "department": "A"},
            {"fullname": "Rico", "nickname": "Rico", "department": "A"},
            {"fullname": "Jerome", "nickname": "Jerome", "department": "A"},
            {"fullname": "Pol T.", "nickname": "Pol T.", "department": "S"},
            {"fullname": "Shy", "nickname": "Shy", "department": "B"},
            {"fullname": "Gab", "nickname": "Gab", "department": "B"},
            {"fullname": "Karl", "nickname": "Karl", "department": "B"},
            {"fullname": "Binsoy", "nickname": "Binsoy", "department": "A"},
            {"fullname": "Wadot", "nickname": "Wadot", "department": "B"},
            {"fullname": "Gen", "nickname": "Gen", "department": "A"},
            {"fullname": "Jade", "nickname": "Jade", "department": "B"},
            {"fullname": "Rachel", "nickname": "Rachel", "department": "A"},
            {"fullname": "Joey", "nickname": "Joey", "department": "A"},
            {"fullname": "Sean Kelly", "nickname": "Sean Kelly", "department": "B"},
        ]

        for player_data in players_data:
            player, created = Player.objects.get_or_create(
                nickname=player_data["nickname"],
                defaults={
                    "fullname": player_data["fullname"],
                    "department": player_data["department"],
                },
            )
            status = "Created" if created else "Already exists"
            self.stdout.write(
                self.style.SUCCESS(f"{status}: {player.nickname}")
            )
